const disa_pert = {
    0: 0,
    10 :165.92,
    20: 327.99,
    30: 508.05 ,
    40: 731.86,
    50: 1041.82,
    60: 1319.65,
    70: 1663.06,
    80: 1933.15,
    90: 2172.39,
    100: 3621.95,
}

const rating_bonus = {
    30:  [{AA : 56, U18Rate: 30.00, O18Rate: 97 }],
    40:  [{AA : 74, U18Rate: 40, O18Rate: 129 }],
    50:  [{AA : 86, U18Rate: 46, O18Rate: 162 }],
    60:  [{AA : 111, U18Rate: 60, O18Rate: 194 }],
    70:  [{AA : 130, U18Rate: 70, O18Rate: 226 }],
    80:  [{AA : 148, U18Rate: 80, O18Rate: 259 }],
    90:  [{AA : 167, U18Rate: 90, O18Rate: 291 }],
    100: [{AA : 185.21, U18Rate: 100.34, O18Rate: 324.12 }],

}

const DP = {
    0: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0}],
    10: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0}],
    20: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0}],
    30: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0},
         {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 60},
         {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 108},
         {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 156},
         {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 48},
         {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 96},
         {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 40},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 104},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 152},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 200},
         {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 88},
         {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 136},
        ],
    40: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0,   monthlypay:0.00  },
        {hasChild: 'no', hasSpouse: 'married', hasParent: 0,   monthlypay:80.00 },
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 1,  monthlypay:144.0 },
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 2,  monthlypay:208.0 },
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 1,   monthlypay:64.00 },
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 2,   monthlypay:128.0 },
        {hasChild: 'yes', hasSpouse: 'single', hasParent: 0,   monthlypay:54.00 },
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay:139.0 },
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay:203.0 },
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay:267.0 },
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1,  monthlypay:118.0 },
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2,  monthlypay:182.0 }
       ],
    50: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0},
         {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 100.00},
         {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 181.00},
         {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 262.00},
         {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 81.00},
         {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 162.00},
         {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 67.00},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 174.00},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 255.00},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 336.00},
         {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 148.00},
         {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 229.00},
        ],
    60: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0},
         {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 121},
         {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 218},
         {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 315},
         {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 97},
         {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 194},
         {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 81},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 209},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 306},
         {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 403},
         {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 178},
         {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 275},
        ],   
    70: [{hasChild: 'no', hasSpouse:'single', hasParent: 0, monthlypay: 0},
        {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 141},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 254},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 367},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 113},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 226},
        {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 94},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 244},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 357},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 470},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 207},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 320},
        ],
    80: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0},
        {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 161},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 290},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 420},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 129},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 258},
        {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 108},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 279},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 408},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 537},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 237},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 366},
        ],
    90: [{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0},
        {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 181},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 326},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 471},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 145},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 290},
        {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 121},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 314},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 459},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 604},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 266},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 411},
        ],
    100:[{hasChild: 'no', hasSpouse: 'single', hasParent: 0, monthlypay: 0},
        {hasChild: 'no', hasSpouse: 'married', hasParent: 0, monthlypay: 201.94},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 1, monthlypay: 364.01},
        {hasChild: 'no',  hasSpouse: 'married', hasParent: 2, monthlypay: 526.08},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 1, monthlypay: 162.07},
        {hasChild: 'no',  hasSpouse: 'single', hasParent: 2, monthlypay: 324.14},
        {hasChild: 'yes', hasSpouse: 'single', hasParent: 0, monthlypay: 135.05},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 0, monthlypay: 349.83},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 1, monthlypay: 511.9},
        {hasChild: 'yes',  hasSpouse: 'married', hasParent: 2, monthlypay: 673.97},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 1, monthlypay: 297.12},
        {hasChild: 'yes',  hasSpouse: 'single', hasParent: 2, monthlypay: 459.19},
        ],
}